### ISSUE TITLE
Chemical formulae are getting scaled in the game

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-chemical-equations#126]
@pixelzoom, something funky changed in master with this sim. In the game, notice how the right side of the equation is scaled down in the below screenshot. Pretty sure it has to do with the length of the chemical formula and the subscript.

<img width="1430" alt="screen shot 2018-05-11 at 10 56 39 am" src="https://user-images.githubusercontent.com/5863899/39936613-454e1b58-550a-11e8-9961-365f33751d00.png">

Seen on macOS 10.13.4 Chrome.

**Comment by pixelzoom** [comment]
Reproduced.  It does appear to be only the longer chemicals that are scaled down.  So there's probably a `maxWidth` that needs to be increased.

**Comment by pixelzoom** [comment]
This problem is not present in the 1.1 release branch (latest 1.1.11).

**Comment by pixelzoom** [comment]
This problem was introduced somewhere between [1.2.0-dev.1](https://bayes.colorado.edu/dev/html/balancing-chemical-equations/1.2.0-dev.1/balancing-chemical-equations_en.html) and [1.2.0-dev.2](https://bayes.colorado.edu/dev/html/balancing-chemical-equations/1.2.0-dev.2/balancing-chemical-equations_en.html?showAnswers) (4/15/18 2:48PM) .  

Unfortunately there's no record in GitHub of when 1.2.0-dev.1 was published.  The directory on bayes has datestamp 1/9/2016, which I think is suspect.

**Comment by pixelzoom** [comment]
For testing purposes, the longest molecule formula in the sim is C<sub>2</sub>H<sub>5</sub>OH.

**Comment by pixelzoom** [comment]
This problem was most likely introduced in the conversion from SubSupText to RichText.   The `maxWidth` applied to the formula in TermNode (see above commit) was resulting in longer formulas being scaled down.  I inspected SubSupText in the release branch dependencies (it was deprecated and deleted from master), and my best guess is that `maxWidth` was formerly being ignored by SubSupText.   In any case, since we want all formulas to have the same font size,  the `maxWidth` is not desirable here, and I've removed it.

@phet-steele please verify in master.

**Comment by pixelzoom** [comment]
I did a little more digging.  In the 1.1 release branch, TermNode has no `maxWidth` setting for the formula.  It was introduced in master in https://github.com/phetsims/balancing-chemical-equations/commit/fc7fb9a59df4e12b3db0d08a07d720437081b395 to address #121, stringTest=xss.  #121 is no longer an issue after moving from SubSupText to RichText, so removing the `maxWidth` is definitely the correct fix.

**Comment by lmulhall-phet** [comment]
@pixelzoom, sorry for not getting around to this sooner. Looks good in master.
