### ISSUE TITLE
fix screenshot

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balancing-chemical-equations#133]
For https://github.com/phetsims/QA/issues/237

While there haven't been any significant design changes that would warrant new screenshots, I discovered that [balancing-chemical-equations-screenshot-alt1](https://github.com/phetsims/balancing-chemical-equations/blob/master/assets/balancing-chemical-equations-screenshot-alt1.png) has the word "Text" layered on top of it, and should be retaken. Since this screenshot needs to be replaced, it might be a good time to retake the other screenshots, so they all use the updated resolution.

**Comment by pixelzoom** [comment]
Nice find @arouinfar.

**Comment by pixelzoom** [comment]
Fixed in master and 1.2 branches.  The "rich diff" is https://github.com/phetsims/balancing-chemical-equations/commit/e2cf5cc07e742bd0daa2a430e7987ae1c4b8b70b?short_path=83bd7c8#diff-83bd7c8c30978b12fa1c1e45b5c6c944.   @arouinfar please verify, close if it looks OK.

I don't think we should bother resizing the images to the new standard size.  If that's really desirable, we should do that as a batch change, applied to all sims.

**Comment by arouinfar** [comment]
Looks good @pixelzoom
