### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-chemical-equations#134]
For https://github.com/phetsims/QA/issues/237
Memory Tests:
Start: 20.5 MB
1 min: 59.7 MB
2 min: 83.5 MB
3 min: 104 MB
4 min: 122 MB
5 min: 145 MB
6 min: 174 MB
7 min: 202 MB
8 min: 219 MB
9 min: 238 MB
10 min: Memory tab crashed when trying to take snapshot

**Comment by pixelzoom** [comment]
@KatieWoe are the above tests from Chrome heap size?

**Comment by KatieWoe** [comment]
Yes.  That is how memory tests are described in the QA book.  Is there another method you'd like me to look at to compare?

**Comment by pixelzoom** [comment]
Nope, just clarifying, and I haven't read the QA book.

**Comment by pixelzoom** [comment]
Original (1.0.0) memory leak testing was done in https://github.com/phetsims/balancing-chemical-equations/issues/96.   The sim hasn't changed much since then, so 2 possibilities come to mind:

(1) The switching to AccordionBox in #125 created a memory leak.

(2) There's a memory leak in common code.

**Comment by pixelzoom** [comment]
The AccordionBoxes exist for the lifetime of the sim (see `BoxNode`), so #125 changes are not the culprit.

**Comment by pixelzoom** [comment]
I took heap snapshots with Chrome 71 + macOS 10.11, and got similar numbers to what @KatieWoe reported above.  The sim is clearly leaking.  But  I don't see anything in heap comparisons that I recognize.  

@jonathanolson would you have a few minutes to take a peek?

**Comment by jonathanolson** [comment]
Traced a leak of `BCEConstants.INCORRECT_ICON` parents back to a constantly growing number of GameFeedbackDialog instances (`GameFeedbackDialog/Panel/VBox/HBox/FontAwesomeNode`).

It doesn't look like GameFeedbackDialog has a dispose method that would remove the common nodes (which should probably be done to avoid that style of leak).

A quick sampling of other objects shows them also leaking through INCORRECT_ICON, so that's probably the only (or largest) leak.

**Comment by pixelzoom** [comment]
To test this in 1.2.0-rc.3, verify that heap snapshots are similar to https://github.com/phetsims/balancing-chemical-equations/issues/134#issuecomment-447069934.

**Comment by KatieWoe** [comment]
1.2.0-rc.2 results:
Start: 19.7 MB
1 min: 33.0
2: 35.1
3: 35.1
4: 36.2
5: 36.0
6: 36.3
7: 36.8
8: 37.6
9: 37.4
10: 36.9

@pixelzoom I think we can confirm this issue
